### PR TITLE
ConnectionManager fix attempt

### PR DESCRIPTION
**Pull request by emilm**
An attempt to fix issue #306

The process exits now, seems to work in a short case I tested. it requires some testing, but it should work.

Also I changed the if / else logics so check if what I did there is correct as well, or if you really are supposed to have if stateChange.state != state.state on top.

### CODE REVIEW

**Comment by mattheworiordan** [comment]
Thanks for the contribution @emilm. I'll get one of the maintainers to review.

**Comment by emilm** [comment]
I hope this is looked into ASAP. I am on a time constraint and I can't have a deamon not shutting down when I signal it to quit. The process will be hanging forever and cause a lot of headache unless this is fixed.

**Comment by paddybyers** [comment]
Hi Emil,

I am looking now

**Comment by emilm** [comment]
Just setting the isDaemon(true) would solve the problem alone, but I guess it's not a proper/clean solution. :)

**Comment by paddybyers** [comment]
> Just setting the isDaemon(true) would solve the problem alone, but I guess it's not a proper/clean solution. :)

Yes, but it is designed to exit cleanly, without being forcibly destroyed. There are environments were you don't have permission to call `setDaemon()`; and if the thread exits abruptly without sending a `CLOSE` message to the server, then it leaves some connection resources on the server for a period of time, which we prefer to avoid.

I will let you know when I have made some progress with it.

**Comment by paddybyers** [comment]
I'm closing this, as we confirmed the other fix resolves the issue (https://github.com/ably/ably-java/commit/6899a0240ef18a45edae3e2a3e46f29728c6f725)

**Pull request closed without merging**
