### PR TITLE
Update javac source and target JDK versions in build.xml

### PR DESCRIPTION
**Pull request by stannedelchev**
Updated javac in build.xml to use JDK 1.6, as discussed in issue #39.

### CODE REVIEW

**Comment by paddybyers** [comment]
Thanks for this but instead I added rules to use different targets for JRE and Android. Can you check if this builds in your environment?

https://github.com/ably/ably-java/compare/build-android-target

**Comment by stannedelchev** [comment]
`build-android-target` is not working for me, same error as first post.
However, everything is ok if I put specific source & target in build.xml like this:

    - <javac srcdir="@{srcdir}" destdir="@{destdir}" classpathref="@{classpath}" source="@{javac.target}" target="@{javac.target}"
    + <javac srcdir="@{srcdir}" destdir="@{destdir}" classpathref="@{classpath}" source="1.6" target="1.6"

**Comment by mattheworiordan** [comment]
@paddybyers I am reopening for now based on @stannedelchev's feedback above.  However, if you feel this is incorrect, please close again and respond.

**Comment by paddybyers** [comment]
Closing; overtaken by the gradle build.

**Pull request closed without merging**
