### PR TITLE
Replace StandardCharset.UTF-8 with Charset.forName(“UTF-8”)

### PR DESCRIPTION
**Pull request by liuzhen2008**
Use Charset.forName directly.

### CODE REVIEW

**Comment by paddybyers** [comment]
LGTM; thanks

**Comment by mattheworiordan** [comment]
@paddybyers what do you suggest we do about the build?  Seems https://github.com/ably/ably-java/issues/330 is still a problem.

@liuzhen2008 thanks very much for the contribution

**Comment by mattheworiordan** [comment]
@liuzhen2008 just a quick update. We looked into what is causing the issues in the CI builds and should have a fix out for that soon (it was a Gradle compatibility issue).  I will then rebase your changes on those fixes to make sure CI is not broken and merge this in and ensure we do a new release.  Thanks again for this contribution.

**Comment by paddybyers** [comment]
Thanks for this; merging now.

**Pull request merged**
