### PR TITLE
feat: introduced retry rules for flaky android push tests

### PR DESCRIPTION
**Pull request by ttypic**
Added retry rules to prevent flaky android push test fail CI

## Summary by CodeRabbit

- **New Features**
	- Introduced a `RetryTestRule` to enhance test reliability by allowing tests to be retried upon failure.
	- Integrated the retry mechanism in the `AndroidPushTest` class, permitting tests to retry up to two times if they fail.
	- Added a cleanup method to ensure a clean state before each test run.
	- Updated the Android testing framework to compile and target SDK version 34, improving compatibility with newer Android features.
	- Modified the testing approach in the GitHub Actions workflow for better execution on the Android emulator, capturing logs on test failures.
	- Updated the version of `android-test` dependency to improve testing capabilities.

These improvements aim to ensure more consistent test outcomes and reduce false negatives during testing.

### CODE REVIEW

**Review by sacOO7 — COMMENTED** [review]
I think JUNIT5 supports intelligent retry for failing tests. 
https://github.com/junit-team/junit5/discussions/3142.
Maybe it's time we should update to JUNIT5

**Comment by sacOO7** [comment]
Not sure if Junit5 really added native support for retries, but surely some hacks available out there https://github.com/junit-team/junit5/issues/1558#issuecomment-414694057

**Comment by ttypic** [comment]
@sacOO7 yes, junit 5 indeed has retry support out of the box, but unfortunately Android runner doesn't support junit 5. Here is issue for this https://issuetracker.google.com/issues/127100532

**Comment by sacOO7** [comment]
> @sacOO7 yes, junit 5 indeed has retry support out of the box, but unfortunately Android runner doesn't support junit 5. Here is issue for this https://issuetracker.google.com/issues/127100532

Sure, let's just make sure existing retry script is stable enough to handle proper retries. Also, there are lot of retry scripts available online -> https://issuetracker.google.com/issues/127100532

**Review by sacOO7 — APPROVED** [review]
LGTM since tests are passing

**Pull request merged**
