### PR TITLE
Push tests.

### PR DESCRIPTION
**Pull request by tcard**
The rest will follow shortly, but this can get work on iOS started.

### CODE REVIEW

**Comment by mattheworiordan** [comment]
Can you confirm what is still outstanding on this?

**Comment by tcard** [comment]
@mattheworiordan This is the stable part only. Then there's the activation state machine, and the PushChannel. Those aren't stable yet.

**Comment by mattheworiordan** [comment]
> @mattheworiordan This is the stable part only. Then there's the activation state machine, and the PushChannel. Those aren't stable yet.

What is the completeness of those sections then?  I was under the impression from the weekly catchups that the Java work was often nearly finished.  If this PR covers `Push.*`, I would assume that there is at least as much work to be done in the "Activate state machine" & `PushChannel`, especially the former given it's the one area with a lot of state complexity no?

**Comment by tcard** [comment]
It's all complete now in a separate PR on top of this one: https://github.com/ably/ably-java/pull/356

**Comment by tcard** [comment]
I've added cherry-picked everything from #356 into this PR, so everything is here now.

**Pull request merged**
