### PR TITLE
Set minimum Android SDK version to 14 (4.0+)

### PR DESCRIPTION
**Pull request by psolstice**

### CODE REVIEW

**Comment by paddybyers** [comment]
Thanks

**Comment by mattheworiordan** [comment]
Out of interest why did we need to bump, and should we put that in the README?

**Comment by mattheworiordan** [comment]
Oops, I see it is mentioned in README.

**Comment by paddybyers** [comment]
> Out of interest why did we need to bump

Since we're now an AAR, the manifest metadata is relevant (and enforced by the toolchain) when including the library; so whereas before it was irrelevant we needed to set it to something, and 4.0 seemed a reasonable balance between being recent enough to be supportable and covering a large proportion of the device population

**Comment by psolstice** [comment]
According to Google we're covering ~98.6% active devices

**Pull request merged**
