### PR TITLE
issues/178: fix fallback

### PR DESCRIPTION
**Pull request by trenouf**
Fixes
https://github.com/ably/ably-java/issues/178

### CODE REVIEW

**Comment by trenouf** [comment]
I've got an intermittent failure in RealtimeConnectFailTest.connect_fail_suspended. Not sure if it was happening before my changes.

**Comment by trenouf** [comment]
I think the failure is new.

**Comment by trenouf** [comment]
The travis builds said:
io.ably.lib.test.realtime.RealtimeSuite > io.ably.lib.test.realtime.ConnectionManagerTest.connectionmanager_reconnect_default_endpoint FAILED
    java.lang.AssertionError at ConnectionManagerTest.java:209

**Comment by paddybyers** [comment]
Reviewing now, but if the failure is only on Travis we will merge this anyway pending further investigation. Travis seems to have trouble with tests where there is a dependency on things happening at specific times.

**Comment by trenouf** [comment]
I still need to track down the first test failure I mentioned: connect_fail_suspended.

**Comment by paddybyers** [comment]
But any transition is first vetted by `checkSuspend()`, which decides, based on how long since the last connection existed, whether to go into `disconnected` or `suspended`. Doesn't that still apply?

**Comment by trenouf** [comment]
Good point, I need to work out why that isn't happening on the second one. So I guess you don't think there is any need to suppress the extra notification from the transport.

**Comment by trenouf** [comment]
It only calls checkSuspend if it was in connecting state. But, on my second event, it's on suspended. I'll add code in handleStateChange to stop it transitioning from suspended to disconnected.

**Comment by paddybyers** [comment]
> I'll add code in handleStateChange to stop it transitioning from suspended to disconnected.

Instead of having explicit code to handle different cases, is it not possible to have it handled uniformly? If handling the disconnection (or failure to connect) of a transport, then check whether to go into disconnected or suspended?

**Comment by trenouf** [comment]
You mean call checkSuspend even when already in disconnected? I fixed the fallback problems by working out what to fall back to in there, so I would need to separate that out again if checkSuspend can be called multiple times for a disconnection or failure to connect.

**Comment by trenouf** [comment]
Anyway, I've done another push.

**Pull request merged**
