### PR TITLE
Fixed BuildConfig problems

### PR DESCRIPTION
**Pull request by psolstice**

### CODE REVIEW

**Comment by mattheworiordan** [comment]
Thanks @psolstice, not clear on what problem specifically this was aiming to solve though?

**Comment by paddybyers** [comment]
> not clear on what problem specifically this was aiming to solve though?

We had a class name conflict with `BuildConfig` being included twice, once by us and once by the android build framework.

**Comment by psolstice** [comment]
> We had a class name conflict with BuildConfig being included twice, once by us and once by the android build framework.

Not quite like that, we had two modules: java and lib each producing their own copy on BuildConfig, I removed BuildConfig from java module. Then I renamed it to AblyBuildConfig to prevent potential conflict with BuildConfig from Android framework. Just in case.

**Comment by paddybyers** [comment]
LGTM

**Pull request merged**
