### PR TITLE
Relocated java-websocket library to bintray

### PR DESCRIPTION
**Pull request by psolstice**

### CODE REVIEW

**Comment by paddybyers** [comment]
Thanks

**Comment by mattheworiordan** [comment]
@psolstice the installation instructions as part of this repo are wrong though, see https://github.com/ably/ably-java#installation?

**Comment by psolstice** [comment]
@mattheworiordan there is 0.8.6prerelease branch with new instruction. We can't publish modified instruction yet because it won't work until we release 0.8.6 and put it on the bintray.

**Comment by mattheworiordan** [comment]
> @mattheworiordan there is 0.8.6prerelease branch with new instruction.

Ok, was not aware of that branch.  I assume you'll do a PR for the changeover in one?

**Comment by psolstice** [comment]
@mattheworiordan yes, of course, I'll do it at some point

**Pull request merged**
