### PR TITLE
Overload publish APIs

### PR DESCRIPTION
**Pull request by gokhanbarisaker**
Resolves: #17

### CODE REVIEW

**Comment by paddybyers** [comment]
LGTM

**Comment by mattheworiordan** [comment]
Where we are calling methods without a listener, it would be good to at least add test coverage to one of these methods so we can be sure that the null listener does not cause any problems.  Would you mind doing that please @gokhanbarisaker

**Comment by gokhanbarisaker** [comment]
Do you want me to check either null listener argument creates any problem within underlying API? or would you like me to just confirm passed null listener argument is delivered to underlying API?

**Comment by mattheworiordan** [comment]
> Do you want me to check either null listener argument creates any problem within underlying API? or would you like me to just confirm passed null listener argument is delivered to underlying API?

I would like to see that that call works so simply copy & paste an existing test that uses a listener and use the new overloaded method.

**Comment by gokhanbarisaker** [comment]
Got it

**Comment by paddybyers** [comment]
Otherwise LGTM, thanks

**Pull request merged**
