### PR TITLE
Various test fixes and disabling to get to 100% pass on travis build

### PR DESCRIPTION
**Pull request by trenouf**

### CODE REVIEW

**Comment by trenouf** [comment]
This won't actually 100% pass on travis because it does not have the test changes to avoid the environment error over on PR https://github.com/ably/ably-java/pull/190

**Comment by trenouf** [comment]
@paddy Could you review'n'merge please. The travis build had loads of failures, but these fixes combined with the other two PRs did give 100% pass earlier when combined together.

**Comment by paddybyers** [comment]
> Could you review'n'merge please.

Yes, provided we raise issues to address the failing tests.

**Comment by trenouf** [comment]
See issue https://github.com/ably/ably-java/issues/159

**Comment by mattheworiordan** [comment]
👍

**Comment by trenouf** [comment]
Also see issue https://github.com/ably/ably-java/issues/191 for the travis openjdk7 thing.

**Pull request merged**
