### PR TITLE
AuthOptions javadoc enhancements and testcases

### PR DESCRIPTION
**Pull request by gokhanbarisaker**
Resolves: #34 

- [x] Javadocs
- [x] Testcases

### CODE REVIEW

**Comment by mattheworiordan** [comment]
Looks good, but no test coverage for `authUrl`, could you not spin up a simple local web server and provide the three object types in the same way?  Any idea why the tests are failing?

**Comment by paddybyers** [comment]
> could you not spin up a simple local web server

We have this: https://github.com/ably/ably-java/blob/master/lib/src/test/java/io/ably/lib/test/rest/RestAuthTest.java#L178

**Comment by mattheworiordan** [comment]
@gokhanbarisaker any thoughts on authUrl tests?

**Comment by gokhanbarisaker** [comment]
I agree with @paddybyers. Current test cases cover authUrl extensively

**Comment by mattheworiordan** [comment]
Ah, OK, I didn't follow tat link :/

**Pull request merged**
