### PR TITLE
Add custom test suite tasks to travis config

### LINKED ISSUE #69: Fix missing JCE dependency on Travis
Crypto tests are failing because missing JCE on Travis. Related discussion is active on travis-ci/travis-ci#832

### PR DESCRIPTION
**Pull request by gokhanbarisaker**
~~Resolves #69~~

- [x] Realtime
- [x] REST

### CODE REVIEW

**Comment by mattheworiordan** [comment]
Excellent

**Comment by paddybyers** [comment]
This assumes that the user has java 8 - should we note this in the readme?

**Comment by mattheworiordan** [comment]
> This assumes that the user has java 8

No, this is only for Travis, so surely it has no bearing on the user?

**Comment by gokhanbarisaker** [comment]
It will be much more clear once we solved the issue.

**Comment by paddybyers** [comment]
LGTM. @gokhanbarisaker you ok for me to merge?

**Comment by gokhanbarisaker** [comment]
Go for it!

**Comment by paddybyers** [comment]
Thanks

**Pull request merged**
