### PR TITLE
Fixed init_default_log_output_stream test on Windows

### PR DESCRIPTION
**Pull request by psolstice**

### CODE REVIEW

**Comment by paddybyers** [comment]
LGTM.

**Comment by paddybyers** [comment]
Thanks.

BTW I suggest that you create branches for the pull requests you create instead of using your `master`, so they can be reviewed and landed in any order, and your master can always track upstream master.

**Comment by psolstice** [comment]
Sure, I used to work with feature branches. This one was trivial so I skipped this step. Next time I'll create a new branch

**Comment by paddybyers** [comment]
> This one was trivial so I skipped this step. Next time I'll create a new branch

Yes, but you can't be sure we'll get around to reviewing it and landing it in the order you expect :)

**Pull request merged**
