### PR TITLE
Feature RTL6d (constraints relating to bundling of queued messages)

### PR DESCRIPTION
**Pull request by amsurana**
1. RTL6d1 - maxMessageSize
2. RTL6d4 - Same type either `Message` or `PresenceMessage`

To implement feature RTL6d, these were required:
a. TO3l8 - define maxMessageSize
b. TO3l8a,b,c,d,e - calculate Message size.

### CODE REVIEW

**Comment by paddybyers** [comment]
Hi @amsurana I'm sorry it took so long to have a look at this. Is it possible to add some tests please?

**Comment by amsurana** [comment]
Okay. I will add some tests around it.

**Comment by paddybyers** [comment]
@amsurana I'd like to resurrect this please. Can you add some tests?

**Comment by amsurana** [comment]
Okay. I will take this up next.

**Comment by QuintinWillison** [comment]
Obsoleted by #567

**Pull request closed without merging**
